"""add publisher, publication_year, dewey_classification to books

Revision ID: 33ae54059875
Revises: 2104aed0b1d8
Create Date: 2026-08-11 18:24:55.288165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33ae54059875'
down_revision: Union[str, None] = '2104aed0b1d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('publisher', sa.String(length=255), nullable=True))
    op.add_column('books', sa.Column('publication_year', sa.Integer(), nullable=True))
    op.add_column('books', sa.Column('dewey_classification', sa.String(length=10), nullable=True))
    op.create_index(op.f('ix_books_dewey_classification'), 'books', ['dewey_classification'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_books_dewey_classification'), table_name='books')
    op.drop_column('books', 'dewey_classification')
    op.drop_column('books', 'publication_year')
    op.drop_column('books', 'publisher')
    # ### end Alembic commands ###