"""add card_number to users

Revision ID: 473a89a29658
Revises: dd7932f38d7b
Create Date: 2026-08-14 22:09:49.808703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '473a89a29658'
down_revision: Union[str, None] = 'dd7932f38d7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remplir les card_number NULL avec une valeur par défaut pour satisfaire la contrainte NOT NULL
    op.execute("UPDATE users SET card_number = 'USR-' || SUBSTRING(id::text, 1, 8) WHERE card_number IS NULL")
    
    op.alter_column('users', 'card_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'card_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###