"""add dewey_id FK to books, prepare removal of dewey_classification text field

Revision ID: 6a847c38c877
Revises: d88070ee9480
Create Date: 2026-08-24 14:50:15.650787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a847c38c877'
down_revision: Union[str, None] = 'd88070ee9480'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Ajouter la nouvelle colonne dewey_id (nullable pour l'instant)
    op.add_column('books', sa.Column('dewey_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_books_dewey_id'), 'books', ['dewey_id'], unique=False)
    op.create_foreign_key('fk_books_dewey_id_dewey_classifications', 'books', 'dewey_classifications', ['dewey_id'], ['id'], ondelete='RESTRICT')
    
    # 2. NE PAS supprimer dewey_classification dans cette migration : on la garde
    # temporairement pour ne perdre aucune donnee historique. Elle sera retiree
    # dans une migration separee une fois la reconciliation manuelle effectuee
    # (les codes texte existants comme "005.8" n'ont pas d'equivalent automatique
    # garanti dans le nouveau referentiel hierarchique tant qu'il n'est pas complet).
    pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_books_dewey_id_dewey_classifications', 'books', type_='foreignkey')
    op.drop_index(op.f('ix_books_dewey_id'), table_name='books')
    op.drop_column('books', 'dewey_id')
    # ### end Alembic commands ###