"""add dewey_id FK to books, prepare removal of dewey_classification text field

Revision ID: b03ff011b21a
Revises: 6a847c38c877
Create Date: 2026-08-24 14:54:35.053779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b03ff011b21a'
down_revision: Union[str, None] = '6a847c38c877'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_books_dewey_classification', table_name='books')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_books_dewey_classification', 'books', ['dewey_classification'], unique=False)
    # ### end Alembic commands ###