"""add dewey_classifications table

Revision ID: d88070ee9480
Revises: 473a89a29658
Create Date: 2026-08-24 13:45:41.608796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd88070ee9480'
down_revision: Union[str, None] = '473a89a29658'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dewey_classifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('label_fr', sa.String(length=255), nullable=False),
    sa.Column('label_en', sa.String(length=255), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['dewey_classifications.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dewey_classifications_code'), 'dewey_classifications', ['code'], unique=True)
    op.create_index(op.f('ix_dewey_classifications_parent_id'), 'dewey_classifications', ['parent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dewey_classifications_parent_id'), table_name='dewey_classifications')
    op.drop_index(op.f('ix_dewey_classifications_code'), table_name='dewey_classifications')
    op.drop_table('dewey_classifications')
    # ### end Alembic commands ###