"""add card_number to users

Revision ID: dd7932f38d7b
Revises: f8e63e569ee9
Create Date: 2026-08-12 17:56:10.590892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd7932f38d7b'
down_revision: Union[str, None] = 'f8e63e569ee9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('card_number', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_users_card_number'), 'users', ['card_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_card_number'), table_name='users')
    op.drop_column('users', 'card_number')
    # ### end Alembic commands ###