"""add qr_code to copies

Revision ID: f8e63e569ee9
Revises: 33ae54059875
Create Date: 2026-08-12 16:06:20.596812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8e63e569ee9'
down_revision: Union[str, None] = '33ae54059875'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('copies', sa.Column('qr_code', sa.String(length=20), nullable=False))
    op.create_index(op.f('ix_copies_qr_code'), 'copies', ['qr_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_copies_qr_code'), table_name='copies')
    op.drop_column('copies', 'qr_code')
    # ### end Alembic commands ###